"""initial2

Revision ID: 15082512e1f8
Revises: caccec6f1839
Create Date: 2024-06-20 08:06:10.895838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15082512e1f8'
down_revision = 'caccec6f1839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vartotojai', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vartotojai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
