"""added_test_to_Vart

Revision ID: caccec6f1839
Revises: 6ed950f16e6f
Create Date: 2024-06-19 16:52:38.308053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caccec6f1839'
down_revision = '6ed950f16e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vartotojai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vartotojai', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
